spring.application.name=Register

spring.datasource.url=jdbc:postgresql://dpg-d4hvi2p5pdvs739fuan0-a.oregon-postgres.render.com:5432/registration_3cnv
spring.datasource.username=database
spring.datasource.password=Z7y1msngYhWfn22jr8IYuNYMwSxBqKl2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
